# Site settings
title: Питон и КИЛИ

baseurl: ""
url: https://pylinda.github.io
git_address: https://github.com/pylinda/pylinda.github.io
git_edit_address: https://github.com/pylinda/pylinda.github.io/blob/master

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag

exclude:
  - README.md
  - docker-compose.yml

timezone: Europe/Moscow
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:path
    output: true
